name: Build and Deploy

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Set up Node.js environment for Backend
      working-directory: ./Backend
      run: |
        apt-get update && apt-get install -y curl
        curl -fsSL https://deb.nodesource.com/setup_20.x | bash -
        apt-get install -y nodejs

    - name: Install dependencies and build Backend
      working-directory: ./Backend
      run: |
        npm install
        npm run build

    - name: Build Docker image for Backend
      working-directory: ./Backend
      run: |
        docker build -t my-backend-image .

    - name: Set up Node.js environment for Mobile
      working-directory: ./Mobile
      run: |
        apt-get update && apt-get install -y curl
        curl -fsSL https://deb.nodesource.com/setup_20.x | bash -
        apt-get install -y nodejs

    - name: Install dependencies and build Mobile
      working-directory: ./Mobile
      run: |
        npm install
        npm run build
