name: Node.js CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [20.x]

    steps:
    - name: Install and build Backend
      working-directory: ./Backend
      run: |
        npm ci
        npm run build

    - name: Build Docker image
      working-directory: ./Backend
      run: |
        docker build -t my-backend-image .

    - name: Install and build Mobile
      working-directory: ./Mobile
      run: |
        npm ci
        npm run build
