name: Node.js CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [20.x]

    steps:
    - name: Check out repository
      uses: actions/checkout@v4

    - name: Set up Node.js
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'

    # Backend steps
    - name: Install dependencies for Backend
      working-directory: ./Backend
      run: npm ci

    - name: Build Backend
      working-directory: ./Backend
      run: npm run build

    - name: Build Docker image for Backend
      working-directory: ./Backend
      run: docker build -t my-backend-image .

    # Mobile steps
    - name: Install dependencies for Mobile
      working-directory: ./Mobile
      run: npm ci

    - name: Build Mobile
      working-directory: ./Mobile
      run: npm run build
